# Copyright (c) 2026 Oliver Kowalke
# SPDX-License-Identifier: MIT

"""
L4 conformance replay — FizzBee state graphs against the real implementation.

The corpora under ``fizz_corpus/`` are canonical FizzBee state graphs
(exhaustive runs, regenerated by ``make regen-fizz-traces`` when a spec
changes). This module re-derives rooted edge-covering walks from each graph
and replays them against the REAL code — the Python-native stand-in for
FizzBee MBT adapters, which upstream ships only for Go/Java/Rust/TypeScript
(fizzbee plan §5.1 extension; ledger: verify/fizz/README.md).

Refinement mappings and their assertion semantics:

- ``jobs_protocol.fizz`` — step-by-step replay: every model action maps to
  one real ``JobsStore`` call; the model's guard outcome (dst state) must
  match the real accept/``JobStateError`` outcome, and the abstract state
  (job status) must match the store after every step. Properties checked
  per step: J-1 (terminal immutability), J-2 (guard agreement), J-3
  (created_at <= updated_at), J-4 (one row per job), FC-2 (ack honesty).
  Traces are deduped to distinct execution signatures under client
  symmetry and job-id renaming — the model's jobs are independent, so
  interleavings that rename to the same execution are one real run.
- ``tei_fallback.fizz`` — outcome-equivalence replay: the real code runs
  the whole protocol inside one synchronous ``retrieve()`` call, so a trace
  replays as ONE real retrieval with the transport/loader injected from the
  trace's final model state. Asserted: TEI-1 (a body exists only for the
  OK verdict — errors raise, never partial results) and RET-1 (a rerank
  error propagates, outcome FAILED).
- ``retrieval_fusion.fizz`` — outcome-equivalence replay over the
  resolution tail: FUS-1 (REAL implies >= 1 pattern), FUS-2 (REAL implies
  the floor passed), FUS-3 (every fallback carries ``is_fallback``).

Vacuity (repo rule: every oracle must be able to fail): the
``TestConformanceVacuity``-style tests plant one mutant per check family
and assert the harness fires — a cancel write that never lands (FG-15
class), a stale-timestamp writer (J-3 clock-skew class), and an error
swallowing reranker (FG-23 class).

Corpus integrity: ``test_corpus_edge_coverage`` asserts each checked-in
graph still edge-covers 100% of its non-stutter transitions (a stale
corpus — spec changed without regen — fails here, not silently).
"""

from __future__ import annotations

import json
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast
from unittest.mock import MagicMock, patch

import httpx
import pytest
from llama_index.core.schema import NodeWithScore, TextNode

from scripts.fizz_traces import Edge, Graph, cover_edges
from src.errors import JobStateError
from src.patterns.retriever import HybridPatternRetriever
from src.patterns.safe_tei_rerank import SafeTEIReranker
from src.tools.jobs import JobStatus, JobsStore

CORPUS_DIR = Path(__file__).parent / "fizz_corpus"
MODEL_TERMINAL = {"COMPLETED", "FAILED", "CANCELLED"}
JOBS_GUARDS: dict[str, set[str]] = {
    "StartRun": {"PENDING"},
    "Cancel": {"PENDING", "RUNNING"},
    "Complete": {"RUNNING"},
    "Fail": {"RUNNING"},
}
COVER_BUDGET_TRACES = 4000
COVER_BUDGET_LEN = 64

FALLBACK_PATTERN = {
    "name": "layered-monolith",
    "category": "structural",
    "context": "Single deployable application organized into horizontal layers.",
    "benefits": ["Simplicity"],
    "tradeoffs": ["Coupling"],
    "quality_attributes": {
        "maintainability": 6,
        "scalability": 4,
        "reliability": 6,
        "security": 6,
        "performance": 5,
    },
    "suitable_domains": ["traditional-web"],
    "best_practices": [],
}
REAL_PATTERN = {
    "name": "microservices",
    "category": "structural",
    "context": "Distributed system of independently deployable services.",
    "benefits": ["Scalability"],
    "tradeoffs": ["Operational complexity"],
    "quality_attributes": {
        "maintainability": 7,
        "scalability": 9,
        "reliability": 7,
        "security": 6,
        "performance": 8,
    },
    "suitable_domains": ["microservices"],
    "best_practices": [],
}


class ConformanceViolation(AssertionError):
    """A replayed model trace diverged from the real implementation."""


@dataclass(frozen=True)
class Step:
    action: str
    src: dict[str, Any]
    dst: dict[str, Any]


@dataclass(frozen=True)
class Trace:
    trace_id: str
    steps: tuple[Step, ...]


def _load_graph(spec: str) -> Graph:
    path = CORPUS_DIR / f"{spec}.json"
    if not path.exists():
        raise FileNotFoundError(
            f"conformance corpus missing: {path} — run `make regen-fizz-traces`"
        )
    raw = json.loads(path.read_text(encoding="utf-8"))
    if raw.get("schema") != 1:
        raise ValueError(f"unsupported corpus schema in {path}: {raw.get('schema')}")
    graph = Graph(nodes=raw["nodes"], adj={i: [] for i in range(len(raw["nodes"]))})
    for edge in raw["edges"]:
        graph.adj[edge["from"]].append(Edge(name=edge["action"], dest=edge["to"]))
    for src in graph.adj:
        graph.adj[src].sort(key=lambda e: (e.name, e.dest))
    return graph


def _load_traces(spec: str) -> list[Trace]:
    graph = _load_graph(spec)
    walks, uncovered = cover_edges(graph, COVER_BUDGET_TRACES, COVER_BUDGET_LEN)
    if uncovered:
        pytest.fail(
            f"corpus {spec} cannot be edge-covered within budget "
            f"({len(uncovered)} edges left) — raise COVER_BUDGET_TRACES"
        )
    return [
        Trace(
            trace_id=f"{spec}#T{i + 1:03d}",
            steps=tuple(
                Step(action=name, src=graph.nodes[src], dst=graph.nodes[dest])
                for src, name, dest in walk
            ),
        )
        for i, walk in enumerate(walks)
    ]


Signature = tuple[Any, ...]


def _signature_replays(spec: str, signature: Callable[[Trace], Any]) -> list[tuple[Signature, Trace]]:
    seen: dict[Signature, Trace] = {}
    for trace in _load_traces(spec):
        sig = signature(trace)
        if sig is not None:
            seen.setdefault(sig, trace)
    return [(sig, trace) for sig, trace in sorted(seen.items(), key=lambda kv: repr(kv[0]))]


# ---------------------------------------------------------------------------
# jobs_protocol — step-by-step replay against the real JobsStore
# ---------------------------------------------------------------------------


def _jobs_signature(trace: Trace) -> Signature:
    client_sym: dict[str, str] = {}
    jid_sym: dict[str, str] = {}
    sig: list[Any] = []
    for step in trace.steps:
        role, _, name = step.action.rpartition(".")
        if name == "Idle":
            continue
        client_sym.setdefault(role, f"c{len(client_sym)}")
        store = step.dst["JobStore#0"]
        if name == "Submit":
            jid_sym.setdefault(f"j{store['next_jid'] - 1}", f"j{len(jid_sym)}")
        inflight = step.dst[role].get("inflight")
        statuses = tuple(
            sorted((jid_sym[jid], status) for jid, status in store["status"].items())
        )
        sig.append((client_sym[role], name, jid_sym.get(inflight), statuses))
    return tuple(sig)


class _JobsReplay:
    """Element→code map (verify/fizz/jobs_protocol.fizz header):
    Submit ↔ create_job; StartRun ↔ set_running; Cancel ↔ set_cancelled;
    Complete ↔ set_completed; Fail ↔ set_failed; JobStore ↔ JobsStore.
    """

    def __init__(self, store: JobsStore) -> None:
        self._store = store
        self._jids: dict[str, str] = {}
        self._terminal: dict[str, tuple[str, str | None]] = {}
        self._acks: set[str] = set()

    async def replay(self, trace: Trace) -> None:
        for step in trace.steps:
            await self._apply(step)
            await self._check(step)

    async def _apply(self, step: Step) -> None:
        role, _, name = step.action.rpartition(".")
        if name == "Idle":
            return
        store = step.dst["JobStore#0"]
        if name == "Submit":
            model_jid = f"j{store['next_jid'] - 1}"
            self._jids[model_jid] = await self._store.create_job(
                requirements="req", domain="dom"
            )
            return
        model_jid = step.src[role]["inflight"]
        if model_jid is None:
            raise AssertionError(f"{step.action}: no inflight in src state — unmapped action?")
        real_jid = self._jids[model_jid]
        src_status = step.src["JobStore#0"]["status"][model_jid]
        expected_success = src_status in JOBS_GUARDS[name]
        try:
            await self._transition(name, real_jid)
            success = True
        except JobStateError:
            success = False
        if success != expected_success:
            raise ConformanceViolation(
                f"{step.action} [{step.src['JobStore#0']['status']}]: {role}.{name} "
                f"from {src_status}: model says "
                f"{'accept' if expected_success else 'reject'}, real store "
                f"{'accepted' if success else 'rejected'} (J-2 guard divergence)"
            )

    async def _transition(self, name: str, real_jid: str) -> None:
        if name == "StartRun":
            await self._store.set_running(real_jid)
        elif name == "Cancel":
            await self._store.set_cancelled(real_jid)
        elif name == "Complete":
            await self._store.set_completed(real_jid, '{"result": "ok"}')
        elif name == "Fail":
            await self._store.set_failed(real_jid, "boom")
        else:
            raise AssertionError(f"unmapped jobs action: {name}")

    async def _check(self, step: Step) -> None:
        store = step.dst["JobStore#0"]
        for model_jid, model_status in store["status"].items():
            row = await self._store.get_job(self._jids[model_jid])
            if row is None:
                raise ConformanceViolation(
                    f"{step.action}: job {model_jid} missing from store (J-4)"
                )
            if row["status"] != model_status.lower():
                raise ConformanceViolation(
                    f"{step.action}: job {model_jid} status divergence — "
                    f"model {model_status}, real {row['status']}"
                )
            if model_status in MODEL_TERMINAL:
                seen = self._terminal.setdefault(model_jid, (model_status, row["result"]))
                if seen[0] != model_status or seen[1] != row["result"]:
                    raise ConformanceViolation(
                        f"{step.action}: terminal job {model_jid} left "
                        f"{seen[0]}/{seen[1]!r} for {model_status}/{row['result']!r} (J-1)"
                    )
            if str(row["created_at"]) > str(row["updated_at"]):
                raise ConformanceViolation(
                    f"{step.action}: job {model_jid} timestamps inverted — "
                    f"created {row['created_at']} > updated {row['updated_at']} (J-3)"
                )
        for role, fields in step.dst.items():
            if not role.startswith("JobClient"):
                continue
            for model_jid in fields.get("ack_cancelled", []):
                self._acks.add(model_jid)
                if not await self._store.is_cancelled(self._jids[model_jid]):
                    raise ConformanceViolation(
                        f"{step.action}: {role} acked cancel of {model_jid} "
                        f"but the store is not CANCELLED (FC-2)"
                    )


# ---------------------------------------------------------------------------
# tei_fallback / retrieval_fusion — outcome-equivalence replay via retrieve()
# ---------------------------------------------------------------------------


def _node(slug: str, score: float) -> NodeWithScore:
    return NodeWithScore(node=TextNode(text=slug, metadata={"slug": slug}), score=score)


def _fused(fused_class: str) -> list[NodeWithScore]:
    if fused_class == "EMPTY":
        return []
    if fused_class == "ONE":
        return [_node("microservices", 0.7)]
    return [
        _node("microservices", 0.7),
        _node("legacy-monolith", 0.6),
        _node("kafka", 0.5),
    ]


def _retriever(
    fused: list[NodeWithScore],
    filter_result: list[dict[str, Any]],
    *,
    floor: float = 0.0,
    reranker_config: bool = True,
) -> HybridPatternRetriever:
    loader = MagicMock()
    loader.filter_by_domain.return_value = filter_result
    loader.get_by_name.return_value = FALLBACK_PATTERN
    dense: MagicMock = MagicMock()
    dense.retrieve.return_value = fused
    bm25: MagicMock = MagicMock()
    bm25.retrieve.return_value = []
    config = (
        MagicMock(base_url="http://tei-sidecar:80", timeout=2.0, max_batch_size=48)
        if reranker_config
        else None
    )
    return HybridPatternRetriever(
        dense_retriever=cast(Any, dense),
        bm25_retriever=cast(Any, bm25),
        pattern_loader=cast(Any, loader),
        min_fusion_score=floor,
        reranker_config=config,
    )


def _tei_transport(verdict: str) -> httpx.MockTransport:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/rerank", f"unexpected TEI path {request.url.path}"
        if verdict == "HTTP_ERROR":
            return httpx.Response(500, text="tei sidecar boom")
        if verdict == "SHAPE_ERROR":
            return httpx.Response(200, json={"detail": "not a list"})
        count = len(json.loads(request.content)["texts"])
        return httpx.Response(
            200,
            json=[
                {"index": count - 1 - i, "score": float(count - i)}
                for i in range(count)
            ],
        )

    return httpx.MockTransport(handler)


def _tei_signature(trace: Trace) -> Signature | None:
    dst = trace.steps[-1].dst
    reranker = dst.get("Reranker#0")
    retriever = dst.get("Retriever#0")
    if reranker is None or retriever is None or retriever["outcome"] == "NONE":
        return None
    return (reranker["verdict"], retriever["fused"], retriever["outcome"])


def _replay_tei(signature: tuple[str, str, str], trace_id: str) -> None:
    verdict, fused_class, model_outcome = signature
    where = f"{trace_id} [{verdict}/{fused_class}]"
    retriever = _retriever(_fused(fused_class), [] if fused_class == "EMPTY" else [REAL_PATTERN])
    raised: RuntimeError | None = None
    outcome: Any = None
    with patch(
        "httpx.Client", return_value=httpx.Client(transport=_tei_transport(verdict))
    ):
        try:
            outcome = retriever.retrieve(
                user_domain="microservices", normalized_domain="microservices"
            )
        except RuntimeError as exc:
            raised = exc
    if model_outcome == "FAILED":
        if raised is None:
            raise ConformanceViolation(
                f"{where}: model says FAILED (rerank error) but real retrieve() "
                f"returned a partial result with {len(outcome.patterns)} pattern(s) (RET-1)"
            )
        expected = "HTTP 500" if verdict == "HTTP_ERROR" else "non-list"
        if expected not in str(raised):
            raise ConformanceViolation(
                f"{where}: rerank error must surface the sidecar cause "
                f"({expected!r} missing): {raised!r} (TEI-1)"
            )
        return
    if raised is not None:
        raise ConformanceViolation(
            f"{where}: real retrieve() raised {raised!r} but model outcome is {model_outcome}"
        )
    if model_outcome == "FALLBACK":
        if len(outcome.patterns) != 1 or not outcome.patterns[0][0].get("is_fallback"):
            raise ConformanceViolation(
                f"{where}: model says FALLBACK but real outcome is not a tagged "
                f"fallback: {outcome.patterns!r} (FUS-3)"
            )
        return
    if not outcome.patterns or any(
        pattern.get("is_fallback") for pattern, _ in outcome.patterns
    ):
        raise ConformanceViolation(
            f"{where}: model says REAL but real outcome is empty or "
            f"fallback-tagged: {outcome.patterns!r} (FUS-1)"
        )
    if fused_class == "MANY" and any(
        "rerank_logit" not in pattern for pattern, _ in outcome.patterns
    ):
        raise ConformanceViolation(
            f"{where}: REAL after rerank must carry rerank_logit on every "
            f"pattern (rerank block did not run) (TEI-1)"
        )


def _fusion_signature(trace: Trace) -> Signature | None:
    dst = trace.steps[-1].dst.get("Retriever#0")
    if dst is None or dst["outcome"] == "NONE":
        return None
    return (
        dst["outcome"],
        dst["resolved"] > 0,
        bool(dst["floor_passed"]),
        bool(dst["tagged"]),
    )


def _replay_fusion(
    signature: tuple[str, bool, bool, bool], trace_id: str
) -> None:
    model_outcome, resolved_any, floor_passed, _tagged = signature
    where = f"{trace_id} [{model_outcome}/{resolved_any}/{floor_passed}]"
    floor = 0.05
    if resolved_any and floor_passed:
        fused, filter_result = [_node("microservices", 0.7)], [REAL_PATTERN]
    elif resolved_any:
        fused, filter_result = [_node("microservices", 0.0)], [REAL_PATTERN]
    else:
        fused, filter_result = [], []
    retriever = _retriever(fused, filter_result, floor=floor, reranker_config=False)
    result = retriever.retrieve(
        user_domain="microservices", normalized_domain="microservices"
    )
    if model_outcome == "REAL":
        if not result.patterns:
            raise ConformanceViolation(f"{where}: REAL must resolve >= 1 pattern (FUS-1)")
        best = result.patterns[0][1]
        if best < floor:
            raise ConformanceViolation(
                f"{where}: REAL score {best} below floor {floor} (FUS-2)"
            )
        if any(p.get("is_fallback") for p, _ in result.patterns):
            raise ConformanceViolation(
                f"{where}: REAL outcome carries the fallback tag (FUS-3)"
            )
    elif len(result.patterns) != 1 or not result.patterns[0][0].get("is_fallback"):
        raise ConformanceViolation(
            f"{where}: fallback must carry the is_fallback sentinel (FUS-3)"
        )


# ---------------------------------------------------------------------------
# corpus integrity + conformance replays
# ---------------------------------------------------------------------------

SPECS = ("jobs_protocol", "tei_fallback", "retrieval_fusion")


@pytest.mark.parametrize("spec", SPECS)
def test_corpus_edge_coverage(spec: str) -> None:
    graph = _load_graph(spec)
    _, uncovered = cover_edges(graph, COVER_BUDGET_TRACES, COVER_BUDGET_LEN)
    assert not uncovered, (
        f"{spec}: corpus graph has {len(uncovered)} uncovered edges — "
        "regenerate with `make regen-fizz-traces`"
    )


_JOBS_REPLAYS = _signature_replays("jobs_protocol", _jobs_signature)
_TEI_REPLAYS: list[tuple[tuple[str, str, str], Trace]] = _signature_replays(
    "tei_fallback", _tei_signature
)
_FUSION_REPLAYS: list[tuple[tuple[str, bool, bool, bool], Trace]] = _signature_replays(
    "retrieval_fusion", _fusion_signature
)


@pytest.mark.parametrize("trace", [trace for _, trace in _JOBS_REPLAYS], ids=lambda t: t.trace_id)
@pytest.mark.asyncio
async def test_jobs_protocol_conformance(trace: Trace, jobs_store: JobsStore) -> None:
    await _JobsReplay(jobs_store).replay(trace)


@pytest.mark.parametrize(
    "signature", [sig for sig, _ in _TEI_REPLAYS], ids=lambda s: f"tei#{s}"
)
def test_tei_fallback_conformance(signature: tuple[str, str, str]) -> None:
    _replay_tei(signature, "tei_fallback")


@pytest.mark.parametrize(
    "signature", [sig for sig, _ in _FUSION_REPLAYS], ids=lambda s: f"fusion#{s}"
)
def test_retrieval_fusion_conformance(signature: tuple[str, bool, bool, bool]) -> None:
    _replay_fusion(signature, "retrieval_fusion")


# ---------------------------------------------------------------------------
# vacuity — planted mutants must fire the harness (FG-15 / J-3 / FG-23 classes)
# ---------------------------------------------------------------------------


class _CancelNeverLandsStore(JobsStore):
    """FG-15 class: the cancel tool acks, but the store write never lands."""

    async def set_cancelled(self, job_id: str) -> None:
        raise JobStateError(job_id=job_id, current_status="pending")


class _StaleClockStore(JobsStore):
    """J-3 clock-skew class: set_running writes a pre-creation updated_at."""

    async def set_running(self, job_id: str) -> None:
        cursor = await self._conn().execute(
            "UPDATE jobs SET status = ?, updated_at = ? WHERE id = ? AND status = ?",
            (JobStatus.RUNNING, "2000-01-01T00:00:00+00:00", job_id, JobStatus.PENDING),
        )
        await self._conn().commit()
        if cursor.rowcount == 0:
            raise JobStateError(job_id=job_id, current_status="pending")


class _ErrorSwallowingReranker(SafeTEIReranker):
    """FG-23 class: an HTTP error still produces a result body."""

    def _call_api(self, query: str, texts: list[str]) -> list[dict[str, Any]]:  # type: ignore[override]
        return [{"index": i, "score": 1.0} for i in range(len(texts))]


def _trace_with(traces: list[Trace], suffix: str, label: str) -> Trace:
    for trace in traces:
        if any(step.action.endswith(suffix) for step in trace.steps):
            return trace
    raise AssertionError(f"corpus lost all {label} traces — vacuity oracle is vacuous")


def _bare_store(cls: type[JobsStore]) -> JobsStore:
    """Instantiate a store subclass without touching the singleton machinery.

    Going through ``cls.get_instance()`` would shadow ``JobsStore._instance``
    on the subclass, so the autouse fixture's teardown would never close the
    leaked aiosqlite connection and the pytest process would hang at exit on
    the orphaned worker thread.
    """
    store = object.__new__(cls)
    store._db = None
    return store


@pytest.mark.asyncio
async def test_vacuity_cancel_write_lost_fires_fc2(jobs_store: JobsStore) -> None:
    broken = _bare_store(_CancelNeverLandsStore)
    await broken._init()
    try:
        trace = _trace_with([t for _, t in _JOBS_REPLAYS], ".Cancel", "Cancel")
        with pytest.raises(ConformanceViolation):
            await _JobsReplay(broken).replay(trace)
    finally:
        if broken._db is not None:
            await broken._db.close()
            broken._db = None


@pytest.mark.asyncio
async def test_vacuity_stale_timestamp_fires_j3(jobs_store: JobsStore) -> None:
    broken = _bare_store(_StaleClockStore)
    await broken._init()
    try:
        trace = _trace_with([t for _, t in _JOBS_REPLAYS], ".StartRun", "StartRun")
        with pytest.raises(ConformanceViolation):
            await _JobsReplay(broken).replay(trace)
    finally:
        if broken._db is not None:
            await broken._db.close()
            broken._db = None


def test_vacuity_error_swallowing_reranker_fires_tei1() -> None:
    error_sigs = [sig for sig, _ in _TEI_REPLAYS if sig[0] == "HTTP_ERROR" and sig[1] == "MANY"]
    assert error_sigs, "corpus lost the HTTP_ERROR/MANY signature — vacuity oracle is vacuous"
    with patch(
        "src.patterns.retriever.SafeTEIReranker",
        return_value=_ErrorSwallowingReranker(base_url="http://tei-sidecar:80"),
    ):
        with pytest.raises(ConformanceViolation):
            _replay_tei(error_sigs[0], "vacuity/FG-23")
