# Copyright (c) 2026 Oliver Kowalke
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
Schema enumerations for MCP architecture pattern system.

This module defines enumerations used across the pattern pipeline including
PatternCategory for classifying architecture patterns, ArchitectureDomain
for pattern suitability filtering, and ArchitectureStyle for architectural
approach names.
"""

from enum import Enum


# FR-19: The system SHALL support pattern categories: messaging, structural, cloud,
# data, ai_cognitive, specialized, api_gateway, coordination, dataflow, presentation
# IC-12: PatternCategory enumeration SHALL have exactly 10 values
class PatternCategory(str, Enum):
    """
    Enumeration of architecture pattern categories.

    This enum categorizes architecture patterns for filtering and selection
    during the pipeline workflow. Uses str mixin for JSON serialization compatibility.

    Categories:
    - MESSAGING: Patterns for inter-component communication
    - STRUCTURAL: Patterns for component organization
    - CLOUD: Cloud-native architectural patterns
    - DATA: Data management and storage patterns
    - AI_COGNITIVE: AI and cognitive system patterns
    - SPECIALIZED: Specialized domain patterns
    - API_GATEWAY: API gateway patterns
    - COORDINATION: Service coordination patterns
    - DATAFLOW: Data flow and processing patterns
    - PRESENTATION: UI and presentation layer patterns
    """

    MESSAGING = "messaging"
    STRUCTURAL = "structural"
    CLOUD = "cloud"
    DATA = "data"
    AI_COGNITIVE = "ai_cognitive"
    SPECIALIZED = "specialized"
    API_GATEWAY = "api_gateway"
    COORDINATION = "coordination"
    DATAFLOW = "dataflow"
    PRESENTATION = "presentation"


# ArchitectureDomain: 376 problem-space domain values for pattern suitability filtering.
# Used by Pattern.suitable_domains, Pattern.unsuitable_domains, DomainVectorIndex, DomainBM25Index.
# Distinct from ArchitectureStyle which describes architectural approach names.
class ArchitectureDomain(str, Enum):
    """
    Enumeration of problem-space architecture domains for pattern suitability filtering.

    This enum defines all valid domain values for Pattern.suitable_domains and
    Pattern.unsuitable_domains fields in pattern JSON files. It is also the source
    corpus for DomainVectorIndex (FAISS) and DomainBM25Index in the hybrid retriever.

    Values are hyphenated-lowercase problem-space descriptors (e.g. e-commerce,
    healthcare-integration, high-frequency-trading). This is distinct from
    ArchitectureStyle which describes the architectural approach (e.g. microservices,
    hexagonal, event-sourcing).

    Source: docs/implementation-guide.md §4.2.1 / docs/pattern-schema.json
    """

    ACTIVITY_FEEDS = "activity-feeds"
    AI_AGENT_ORCHESTRATION = "ai-agent-orchestration"
    AI_PRODUCTS = "ai-products"
    ALWAYS_ONLINE_DESKTOP_APPS = "always-online-desktop-apps"
    ANOMALY_DETECTION = "anomaly-detection"
    API_GATEWAYS = "api-gateways"
    APPLICATION_SERVERS = "application-servers"
    APPLICATIONS_NEEDING_COMPLEX_CROSS_SHARD_JOINS = "applications-needing-complex-cross-shard-joins"
    APPLICATIONS_PLANNING_EVENTUAL_EXTRACTION_TO_MICROSERVICES = "applications-planning-eventual-extraction-to-microservices"
    APPLICATIONS_WITH_IDENTICAL_CLIENT_NEEDS = "applications-with-identical-client-needs"
    ARTIFICIAL_INTELLIGENCE = "artificial-intelligence"
    AUDIT_REGULATORY = "audit-regulatory"
    AUDIT_TRAIL_REQUIREMENTS = "audit-trail-requirements"
    AUTONOMIC_SYSTEMS = "autonomic-systems"
    AUTONOMOUS_MOBILE_ROBOTS = "autonomous-mobile-robots"
    AUTONOMOUS_SYSTEMS = "autonomous-systems"
    AUTONOMOUS_VEHICLES = "autonomous-vehicles"
    B2B_INTEGRATION = "b2b-integration"
    BACKEND_FOR_FRONTEND = "backend-for-frontend"
    BACKUP_AND_DISASTER_RECOVERY_SCENARIOS = "backup-and-disaster-recovery-scenarios"
    BANKING_AND_FINANCE = "banking-and-finance"
    BATCH_ANALYTICS_ONLY = "batch-analytics-only"
    BATCH_PROCESSING = "batch-processing"
    BETTING_AND_WAGERING_SYSTEMS = "betting-and-wagering-systems"
    BIG_DATA_ANALYTICS = "big-data-analytics"
    CASES_WHERE_TECHNOLOGY_STACK_HETEROGENEITY_IS_CRITICAL = "cases-where-technology-stack-heterogeneity-is-critical"
    CI_CD_ENVIRONMENTS = "ci-cd-environments"
    CLICKSTREAM_ANALYTICS = "clickstream-analytics"
    CLOUD_FIRST_MANDATE_WITH_NO_REGULATORY_BARRIERS = "cloud-first-mandate-with-no-regulatory-barriers"
    CLOUD_NATIVE = "cloud-native"
    CLOUD_NATIVE_APPLICATIONS = "cloud-native-applications"
    CLOUD_NATIVE_APPLICATIONS_ON_KUBERNETES = "cloud-native-applications-on-kubernetes"
    CLOUD_NATIVE_NATIVE = "cloud-native-native"
    COLLABORATIVE_APPLICATIONS = "collaborative-applications"
    COLLABORATIVE_DOMAINS = "collaborative-domains"
    COMPANIES_UNDERTAKING_MULTI_YEAR_CLOUD_MIGRATION_JOURNEYS = "companies-undertaking-multi-year-cloud-migration-journeys"
    COMPILER_TOOLCHAINS = "compiler-toolchains"
    COMPLEX_BUSINESS_LOGIC = "complex-business-logic"
    COMPLEX_DOMAIN = "complex-domain"
    COMPLEX_DOMAIN_DRIVEN = "complex-domain-driven"
    COMPLEX_DOMAINS = "complex-domains"
    COMPLEX_INTERACTIVE_SYSTEMS = "complex-interactive-systems"
    COMPLEX_LOCAL_TESTING = "complex-local-testing"
    COMPLEX_SCHEDULING = "complex-scheduling"
    COMPLEX_WINDOW_FUNCTIONS_OVER_FULL_HISTORY = "complex-window-functions-over-full-history"
    COMPLIANCE = "compliance"
    CONTENT_MANAGEMENT_SYSTEMS = "content-management-systems"
    COST_SENSITIVE_STORAGE = "cost-sensitive-storage"
    CPU_BOUND_COMPUTATION = "cpu-bound-computation"
    CROSS_LANGUAGE_PLATFORMS = "cross-language-platforms"
    CROSS_ORGANIZATIONAL = "cross-organizational"
    CROSS_PLATFORM_INTEGRATION = "cross-platform-integration"
    CRUD_APPLICATIONS = "crud-applications"
    DATA_DRIVEN_WEB_APPLICATIONS = "data-driven-web-applications"
    DATA_INTENSIVE_WORKLOADS = "data-intensive-workloads"
    DATA_PIPELINES = "data-pipelines"
    DATA_PROCESSING = "data-processing"
    DATA_SCIENCE_PLATFORMS = "data-science-platforms"
    DATA_TRANSFORMATION_PIPELINES = "data-transformation-pipelines"
    DECISION_SUPPORT_SYSTEMS = "decision-support-systems"
    DESKTOP_APPLICATIONS = "desktop-applications"
    DIRECT_NETWORK_ACCESS_SUFFICIENT = "direct-network-access-sufficient"
    DISASTER_RECOVERY = "disaster-recovery"
    DISTRIBUTED_DATA_PIPELINES = "distributed-data-pipelines"
    DISTRIBUTED_TRANSACTIONS = "distributed-transactions"
    DOMAIN_DRIVEN_DESIGN = "domain-driven-design"
    E_COMMERCE = "e-commerce"
    E_COMMERCE_FLASH_SALES = "e-commerce-flash-sales"
    E_COMMERCE_ORDER_PROCESSING = "e-commerce-order-processing"
    E_COMMERCE_PLATFORMS = "e-commerce-platforms"
    E_COMMERCE_PLATFORMS_WITH_MULTIPLE_PRODUCT_CATEGORIES = "e-commerce-platforms-with-multiple-product-categories"
    EARLY_STAGE_PRODUCTS_WITH_UNCLEAR_SERVICE_BOUNDARIES = "early-stage-products-with-unclear-service-boundaries"
    EARLY_STAGE_STARTUPS = "early-stage-startups"
    EDGE_COMPUTING_BANDWIDTH = "edge-computing-bandwidth"
    ENERGY = "energy"
    ENTERPRISE = "enterprise"
    ENTERPRISE_APPLICATION_INTEGRATION = "enterprise-application-integration"
    ENTERPRISE_APPLICATIONS = "enterprise-applications"
    ENTERPRISE_APPLICATIONS_WITH_DISTINCT_BUSINESS_CAPABILITIES = "enterprise-applications-with-distinct-business-capabilities"
    ENTERPRISE_INTEGRATION = "enterprise-integration"
    ENTERPRISE_SAAS = "enterprise-saas"
    ENTERPRISE_SCALE = "enterprise-scale"
    ENTERPRISE_SOFTWARE = "enterprise-software"
    ENTERPRISE_SYSTEMS_NEEDING_CENTRALIZED_GOVERNANCE = "enterprise-systems-needing-centralized-governance"
    ENTERPRISE_WEB = "enterprise-web"
    ERP_CRM = "erp-crm"
    ETL = "etl"
    EVENT_DRIVEN_ARCHITECTURES = "event-driven-architectures"
    EVENT_DRIVEN_MICROSERVICES = "event-driven-microservices"
    EVENT_DRIVEN_SYSTEMS = "event-driven-systems"
    EVENT_DRIVEN_WORKFLOWS = "event-driven-workflows"
    EVENT_DRIVEN_WORKLOADS = "event-driven-workloads"
    EXPERT_SYSTEMS = "expert-systems"
    EXTENSIBLE_APPLICATIONS = "extensible-applications"
    EXTREME_LOW_LATENCY = "extreme-low-latency"
    FEW_SERVICES = "few-services"
    FILE_PROCESSING = "file-processing"
    FINANCE_BANKING = "finance-banking"
    FINANCIAL = "financial"
    FINANCIAL_COMPLIANCE = "financial-compliance"
    FINANCIAL_SERVICES = "financial-services"
    FINANCIAL_SYSTEMS = "financial-systems"
    FINANCIAL_TRADING = "financial-trading"
    FINANCIAL_TRADING_PLATFORMS = "financial-trading-platforms"
    FINTECH = "fintech"
    FIXED_PREDICTABLE_VOLUMES = "fixed-predictable-volumes"
    FLAT_SCREEN_BASED_INTERFACES = "flat-screen-based-interfaces"
    FRAUD_DETECTION = "fraud-detection"
    FREQUENTLY_CORRECTING_DATA = "frequently-correcting-data"
    GAME_UI_ARCHITECTURES = "game-ui-architectures"
    GAMING_SERVERS = "gaming-servers"
    GEOGRAPHICAL_EXPANSION_WITHOUT_BUILDING_DATACENTERS = "geographical-expansion-without-building-datacenters"
    GENERAL = "general"
    GLOBAL_DISTRIBUTION = "global-distribution"
    GOVERNMENT = "government"
    GOVERNMENT_SYSTEMS = "government-systems"
    GPU_SPECIALIZED_HARDWARE = "gpu-specialized-hardware"
    GREENFIELD_MICROSERVICES = "greenfield-microservices"
    GREENFIELD_PROJECTS_WITH_NO_LEGACY_CONSTRAINTS = "greenfield-projects-with-no-legacy-constraints"
    GREENFIELD_SIMPLE_SERVICES = "greenfield-simple-services"
    GUI_APPLICATIONS = "gui-applications"
    HARD_REAL_TIME_CONTROL = "hard-real-time-control"
    HARD_REAL_TIME_SYSTEMS = "hard-real-time-systems"
    HEALTHCARE = "healthcare"
    HEALTHCARE_INTEGRATION = "healthcare-integration"
    HEALTHCARE_MEDICAL = "healthcare-medical"
    HEAVY_PLUGIN_INTERDEPENDENCIES = "heavy-plugin-interdependencies"
    HETEROGENEOUS_SYSTEMS = "heterogeneous-systems"
    HIERARCHICAL_TASK_DECOMPOSITION = "hierarchical-task-decomposition"
    HIGH_CONCURRENCY = "high-concurrency"
    HIGH_DIMENSIONAL_PATTERN_RECOGNITION = "high-dimensional-pattern-recognition"
    HIGH_FREQUENCY_TRADING = "high-frequency-trading"
    HIGH_SCALING_DISTRIBUTED = "high-scaling-distributed"
    HIGH_SCALING_NEEDS = "high-scaling-needs"
    HIGH_THROUGHPUT_STREAMING = "high-throughput-streaming"
    HIGH_THROUGHPUT_TRADING = "high-throughput-trading"
    HIGH_TRAFFIC = "high-traffic"
    HIGH_TRAFFIC_PORTALS = "high-traffic-portals"
    HIGH_TRAFFIC_SYSTEMS = "high-traffic-systems"
    HIGHLY_CONFIGURABLE_PLATFORMS = "highly-configurable-platforms"
    HIGHLY_INTERACTIVE_UI = "highly-interactive-ui"
    HUMAN_OVERSIGHT_SYSTEMS = "human-oversight-systems"
    IDE_BROWSERS = "ide-browsers"
    IMAGE_PROCESSING = "image-processing"
    INDUSTRIAL_AUTOMATION = "industrial-automation"
    INSURANCE = "insurance"
    INTERACTIVE_UI = "interactive-ui"
    INTERNAL_SERVICES_WHERE_DIRECT_COMMUNICATION_SUFFICES = "internal-services-where-direct-communication-suffices"
    INTERNAL_TOOLS = "internal-tools"
    INVENTORY_MANAGEMENT = "inventory-management"
    IOT = "iot"
    IOT_DATA_INGESTION = "iot-data-ingestion"
    IOT_DATA_PROCESSING = "iot-data-processing"
    IOT_DEVICE_MANAGEMENT = "iot-device-management"
    IOT_INDUSTRIAL = "iot-industrial"
    IOT_SENSOR_DATA = "iot-sensor-data"
    IOT_SENSOR_NETWORKS = "iot-sensor-networks"
    IOT_SENSOR_PROCESSING = "iot-sensor-processing"
    KUBERNETES = "kubernetes"
    LARGE_SCALE_DISTRIBUTED_SYSTEMS = "large-scale-distributed-systems"
    LARGE_TEAMS = "large-teams"
    LATENCY_SENSITIVE_EXTREME = "latency-sensitive-extreme"
    LEDGER_BOOKKEEPING = "ledger-bookkeeping"
    LEGACY_MODERNIZATION = "legacy-modernization"
    LEGACY_SYSTEM_INTEGRATION = "legacy-system-integration"
    LEGAL = "legal"
    LEGAL_COMPLIANCE = "legal-compliance"
    LEGAL_REGULATORY = "legal-regulatory"
    LIMITED_OPERATIONAL_MATURITY = "limited-operational-maturity"
    LOG_ANALYSIS = "log-analysis"
    LONG_LIVED_APPLICATIONS = "long-lived-applications"
    LONG_RUNNING_PROCESSES = "long-running-processes"
    LONG_RUNNING_SYSTEMS = "long-running-systems"
    LOW_BUDGET = "low-budget"
    LOW_COMPLEXITY_PROJECTS = "low-complexity-projects"
    LOW_COMPLEXITY_SINGLE_SERVICE = "low-complexity-single-service"
    LOW_CONCURRENCY_SINGLE_NODE_APPS = "low-concurrency-single-node-apps"
    LOW_CONCURRENCY_SYSTEMS = "low-concurrency-systems"
    LOW_DATA_IMPLICIT_PATTERNS = "low-data-implicit-patterns"
    LOW_DATA_VOLUME_MONITORING = "low-data-volume-monitoring"
    LOW_DATA_VOLUME_SCENARIOS = "low-data-volume-scenarios"
    LOW_HISTORY_REQUIREMENTS = "low-history-requirements"
    LOW_LATENCY = "low-latency"
    LOW_LATENCY_CRITICAL_SYSTEMS = "low-latency-critical-systems"
    LOW_LATENCY_LOCAL_CALLS = "low-latency-local-calls"
    LOW_LATENCY_LOCAL_OPERATIONS = "low-latency-local-operations"
    LOW_LATENCY_REAL_TIME = "low-latency-real-time"
    LOW_LATENCY_REQUIRED = "low-latency-required"
    LOW_LATENCY_REQUIREMENTS = "low-latency-requirements"
    LOW_LATENCY_REQUIREMENTS_THAT_CANNOT_TOLERATE_ADDITIONAL_HOP = "low-latency-requirements-that-cannot-tolerate-additional-hop"
    LOW_MATURITY = "low-maturity"
    LOW_ML_REQUIREMENTS = "low-ml-requirements"
    LOW_TRAFFIC = "low-traffic"
    LOW_TRAFFIC_APPLICATIONS = "low-traffic-applications"
    LOYALTY_PROGRAMS = "loyalty-programs"
    MANUFACTURING = "manufacturing"
    MEDIA_PROCESSING = "media-processing"
    MERGERS_ACQUISITIONS = "mergers-acquisitions"
    MESSAGING_SYSTEMS = "messaging-systems"
    MICROSERVICES = "microservices"
    MICROSERVICES_ARCHITECTURE = "microservices-architecture"
    MICROSERVICES_ARCHITECTURES = "microservices-architectures"
    MICROSERVICES_ARCHITECTURES_WITH_MULTIPLE_BACKEND_SERVICES = "microservices-architectures-with-multiple-backend-services"
    MICROSERVICES_COMMUNICATION = "microservices-communication"
    MICROSERVICES_ECOSYSTEM = "microservices-ecosystem"
    MICROSERVICES_READY = "microservices-ready"
    MICROSERVICES_SCALE = "microservices-scale"
    MIDDLEWARE = "middleware"
    MINIMAL_EXTERNAL_INTEGRATIONS = "minimal-external-integrations"
    MINIMAL_INFRASTRUCTURE_OVERHEAD = "minimal-infrastructure-overhead"
    ML_ENGINEERING = "ml-engineering"
    ML_TRAINING_PIPELINES_REQUIRING_GLOBAL_BATCH_PROCESSING = "ml-training-pipelines-requiring-global-batch-processing"
    MOBILE_APPLICATIONS = "mobile-applications"
    MOBILE_FIRST_APPLICATIONS = "mobile-first-applications"
    MONOLITH_OR_FEWER_THAN_3_SERVICES = "monolith-or-fewer-than-3-services"
    MONOLITH_WITHOUT_SCALING_NEEDS = "monolith-without-scaling-needs"
    MULTI_AGENT_AI_SYSTEMS = "multi-agent-ai-systems"
    MULTI_AGENT_COORDINATION = "multi-agent-coordination"
    MULTI_BOUNDED_CONTEXTS = "multi-bounded-contexts"
    MULTI_CLIENT_SYSTEMS = "multi-client-systems"
    MULTI_CLUSTER = "multi-cluster"
    MULTI_DIVISIONAL = "multi-divisional"
    MULTI_EXTERNAL_INTEGRATIONS = "multi-external-integrations"
    MULTI_PROTOCOL_ENVIRONMENTS = "multi-protocol-environments"
    MULTI_SERVICE_BUSINESS_WORKFLOWS = "multi-service-business-workflows"
    MULTI_TEAM = "multi-team"
    MULTI_TEAM_ORGANIZATIONS = "multi-team-organizations"
    MULTI_TENANT_PLATFORMS = "multi-tenant-platforms"
    MULTI_TENANT_SAAS = "multi-tenant-saas"
    MULTI_USER_COLLABORATIVE_SYSTEMS = "multi-user-collaborative-systems"
    MULTI_WINDOW_APPLICATIONS = "multi-window-applications"
    MULTIPLE_SERVICES_SAME_DATA = "multiple-services-same-data"
    MULTIPLE_TEAMS = "multiple-teams"
    MVP = "mvp"
    NATURAL_LANGUAGE_PROCESSING = "natural-language-processing"
    NOTIFICATIONS = "notifications"
    OPERATING_SYSTEMS = "operating-systems"
    ORDER_MANAGEMENT = "order-management"
    ORGANIZATIONS_IN_HEAVILY_REGULATED_INDUSTRIES = "organizations-in-heavily-regulated-industries"
    ORGANIZATIONS_WITH_SEPARATE_CLIENT_TEAMS = "organizations-with-separate-client-teams"
    ORGANIZATIONS_WITHOUT_STREAMING_INFRASTRUCTURE = "organizations-without-streaming-infrastructure"
    PATTERN_RECOGNITION = "pattern-recognition"
    PAYMENT_PROCESSING = "payment-processing"
    PERFORMANCE_CRITICAL_REAL_TIME = "performance-critical-real-time"
    PERSISTENT_WEBSOCKET_CONNECTIONS = "persistent-websocket-connections"
    PLATFORM_ECOSYSTEMS = "platform-ecosystems"
    POLYGLOT_PERSISTENCE_NEEDS = "polyglot-persistence-needs"
    PROBABILISTIC_REASONING = "probabilistic-reasoning"
    PRODUCT_PLATFORMS = "product-platforms"
    PROJECTS_WITH_LIMITED_OPERATIONAL_MATURITY = "projects-with-limited-operational-maturity"
    PROTOTYPES = "prototypes"
    PUBLIC_APIS_REQUIRING_RATE_LIMITING_AND_AUTHENTICATION = "public-apis-requiring-rate-limiting-and-authentication"
    PURELY_SYNCHRONOUS_WORKLOADS = "purely-synchronous-workloads"
    QUEUE_PROCESSING = "queue-processing"
    RANDOM_DATA_ACCESS = "random-data-access"
    RAPID_PROTOTYPING = "rapid-prototyping"
    RAPIDLY_EVOLVING_DOMAINS = "rapidly-evolving-domains"
    REAL_TIME_ANALYTICS = "real-time-analytics"
    REAL_TIME_ANALYTICS_DASHBOARDS = "real-time-analytics-dashboards"
    REAL_TIME_COLLABORATIVE = "real-time-collaborative"
    REAL_TIME_DASHBOARDS = "real-time-dashboards"
    REAL_TIME_DETERMINISTIC = "real-time-deterministic"
    REAL_TIME_GAMING = "real-time-gaming"
    REAL_TIME_INTERACTIVE_SYSTEMS = "real-time-interactive-systems"
    REAL_TIME_PROCESSING = "real-time-processing"
    REAL_TIME_SYSTEMS = "real-time-systems"
    REAL_TIME_SYSTEMS_WHERE_ANY_LATENCY_OVERHEAD_IS_UNACCEPTABLE = "real-time-systems-where-any-latency-overhead-is-unacceptable"
    RECOMMENDATION_ENGINES = "recommendation-engines"
    RECOMMENDATION_SYSTEMS = "recommendation-systems"
    REGULATED_INDUSTRIES = "regulated-industries"
    REGULATORY_COMPLIANCE = "regulatory-compliance"
    REQUEST_RESPONSE = "request-response"
    REQUEST_RESPONSE_APIS = "request-response-apis"
    RESOURCE_CONSTRAINED_ENVIRONMENTS = "resource-constrained-environments"
    RESTFUL_APIS = "restful-apis"
    ROBOTIC_SYSTEMS = "robotic-systems"
    RULE_BASED_SYSTEMS = "rule-based-systems"
    RULE_ENGINES = "rule-engines"
    SAAS_APPLICATIONS_WITH_MULTI_TENANT_REQUIREMENTS = "saas-applications-with-multi-tenant-requirements"
    SCHEDULED_TASKS = "scheduled-tasks"
    SECURITY_SENSITIVE_WITHOUT_CARE = "security-sensitive-without-care"
    SELF_HEALING_SYSTEMS = "self-healing-systems"
    SENSOR_FUSION = "sensor-fusion"
    SERVER_SIDE_RENDERING = "server-side-rendering"
    SERVER_SIDE_WEB_RENDERING = "server-side-web-rendering"
    SERVERLESS = "serverless"
    SESSION_MANAGEMENT_SYSTEMS = "session-management-systems"
    SHORT_DURATION_TRANSACTIONS_WHERE_2PC_IS_FEASIBLE = "short-duration-transactions-where-2pc-is-feasible"
    SHORT_LIVED_PROJECTS = "short-lived-projects"
    SIGNAL_PROCESSING = "signal-processing"
    SIMPLE_APPLICATIONS = "simple-applications"
    SIMPLE_CRUD = "simple-crud"
    SIMPLE_CRUD_APPLICATIONS = "simple-crud-applications"
    SIMPLE_DOMAINS = "simple-domains"
    SIMPLE_LOCAL_COMMUNICATION = "simple-local-communication"
    SIMPLE_POINT_TO_POINT = "simple-point-to-point"
    SIMPLE_REQUEST_RESPONSE = "simple-request-response"
    SIMPLE_SINGLE_TASK_AUTOMATION = "simple-single-task-automation"
    SIMPLE_SINGLE_VIEW_APPLICATIONS = "simple-single-view-applications"
    SINGLE_ALGORITHM = "single-algorithm"
    SINGLE_CLIENT_SINGLE_SERVICE = "single-client-single-service"
    SINGLE_CODEBASE_PREFERENCES = "single-codebase-preferences"
    SINGLE_DOMAIN = "single-domain"
    SINGLE_ORGANIZATION = "single-organization"
    SINGLE_PERSISTENCE_LAYER = "single-persistence-layer"
    SINGLE_SERVICE_APPLICATIONS = "single-service-applications"
    SINGLE_THREADED_ENVIRONMENTS = "single-threaded-environments"
    SMALL_APPLICATIONS = "small-applications"
    SMALL_LOOSELY_COUPLED_SYSTEMS = "small-loosely-coupled-systems"
    SMALL_TEAM_PROJECTS = "small-team-projects"
    SMALL_TEAMS = "small-teams"
    SMALL_TEAMS_LACKING_OPERATIONAL_INFRASTRUCTURE = "small-teams-lacking-operational-infrastructure"
    SMALL_TEAMS_SIMPLE_REQUIREMENTS = "small-teams-simple-requirements"
    SMALL_TEAMS_WITH_LOW_OPERATIONAL_MATURITY = "small-teams-with-low-operational-maturity"
    SMALL_TEAMS_WITHOUT_DEDICATED_INFRASTRUCTURE_OPS = "small-teams-without-dedicated-infrastructure-ops"
    SMALL_TEAMS_WITHOUT_FULLSTACK_CAPABILITIES = "small-teams-without-fullstack-capabilities"
    SMALL_TO_MEDIUM_SCALE_DATA_PROCESSING = "small-to-medium-scale-data-processing"
    SMALL_TO_MEDIUM_TEAMS = "small-to-medium-teams"
    SMART_CITIES = "smart-cities"
    SMART_RETAIL = "smart-retail"
    SPACE_MISSION_CONTROL = "space-mission-control"
    SPEECH_RECOGNITION = "speech-recognition"
    STARTUP = "startup"
    STARTUP_POCS = "startup-pocs"
    STARTUPS_EARLY_STAGE = "startups-early-stage"
    STATE_DEPENDENT_PROCESSING = "state-dependent-processing"
    STATEFUL_COMPUTE_INTENSIVE_TASKS = "stateful-compute-intensive-tasks"
    STATIC_REFERENCE_DATA = "static-reference-data"
    STATIC_REQUIREMENTS = "static-requirements"
    STEADY_PREDICTABLE_LOADS_WITH_NO_NEED_FOR_BURSTING = "steady-predictable-loads"
    STEADY_HIGH_TRAFFIC = "steady-high-traffic"
    STREAM_PROCESSING = "stream-processing"
    STREAMING = "streaming"
    STREAMING_ANALYTICS_PREPARATION = "streaming-analytics-preparation"
    STRICT_DATA_RESIDENCY_REQUIREMENTS = "strict-data-residency-requirements"
    STRICT_STATIC_ANALYSIS = "strict-static-analysis"
    STRONG_CONSISTENCY_REQUIRED = "strong-consistency-required"
    STRONG_CONSISTENCY_REQUIREMENTS = "strong-consistency-requirements"
    STRONG_IMMEDIATE_CONSISTENCY = "strong-immediate-consistency"
    STRONG_TRANSACTION = "strong-transaction"
    STRONGLY_CONSISTENT = "strongly-consistent"
    STRONGLY_CONSISTENT_SINGLE_ENTITY = "strongly-consistent-single-entity"
    SUB_MILLISECOND_RESPONSE_REQUIREMENTS = "sub-millisecond-response-requirements"
    SUPPLY_CHAIN = "supply-chain"
    SYSTEMS_REQUIRING_AUDIT_TRAILS = "systems-requiring-audit-trails"
    SYSTEMS_REQUIRING_STRONG_ACID_TRANSACTIONS = "systems-requiring-strong-acid-transactions"
    SYSTEMS_REQUIRING_STRONG_CONSISTENCY = "systems-requiring-strong-consistency"
    SYSTEMS_REQUIRING_STRONG_CONSISTENCY_WITHIN_MODULES = "systems-requiring-strong-consistency-within-modules"
    SYSTEMS_REQUIRING_STRONG_IMMEDIATE_CONSISTENCY = "systems-requiring-strong-immediate-consistency"
    SYSTEMS_WITH_STRONG_CONSISTENCY_REQUIREMENTS = "systems-with-strong-consistency-requirements"
    SYSTEMS_WITH_VERY_HIGH_TRANSACTION_THROUGHPUT_REQUIREMENTS = "systems-with-very-high-transaction-throughput-requirements"
    TEAM_EXPERIENCE_LOW = "team-experience-low"
    TEAMS_LACKING_OPERATIONAL_EXPERTISE = "teams-lacking-operational-expertise"
    TEAMS_SIZED_5_50_WITH_DOMAIN_ALIGNED_MODULE_OWNERSHIP = "teams-sized-5-50-with-domain-aligned-module-ownership"
    TEAMS_UNFAMILIAR_WITH_EVENT_DRIVEN_PATTERNS = "teams-unfamiliar-with-event-driven-patterns"
    TEAMS_UNFAMILIAR_WITH_REFLECTION = "teams-unfamiliar-with-reflection"
    TEAMS_WITH_BATCH_FOCUSED_EXPERTISE = "teams-with-batch-focused-expertise"
    TEAMS_WITH_LIMITED_BATCH_STREAM_EXPERTISE = "teams-with-limited-batch-stream-expertise"
    TEAMS_WITHOUT_DISTRIBUTED_SYSTEMS_EXPERTISE = "teams-without-distributed-systems-expertise"
    TECHNICAL_SUPPORT = "technical-support"
    TELECOM_AND_REAL_TIME_MESSAGING = "telecom-and-real-time-messaging"
    TELECOMMUNICATIONS = "telecommunications"
    TICKET_BOOKING_SYSTEMS = "ticket-booking-systems"
    TIGHT_COUPLING_ACCEPTABLE = "tight-coupling-acceptable"
    TIGHTLY_COUPLED = "tightly-coupled"
    TRADITIONAL_WEB = "traditional-web"
    TRAVEL_RESERVATIONS = "travel-reservations"
    ULTRA_LOW_LATENCY_REQUIREMENTS = "ultra-low-latency-requirements"
    VIDEO_ANALYTICS = "video-analytics"
    VOIP_APPLICATIONS = "voip-applications"
    VOLATILE_CORE_FREQUENT_CHANGES = "volatile-core-frequent-changes"
    WEB_APPLICATIONS = "web-applications"
    WEB_SERVERS = "web-servers"
    WEBHOOKS = "webhooks"
    WORKFLOW_SYSTEMS = "workflow-systems"
    WRITE_HEAVY_LOW_READ_WORKLOADS = "write-heavy-low-read-workloads"


# ArchitectureStyle: canonical architectural approach names from pattern JSON files.
# Used as Pattern.name and ArchitectureDesign.overview.style values.
# Distinct from ArchitectureDomain which describes the problem space.
class ArchitectureStyle(str, Enum):
    """
    Enumeration of canonical architectural approach names from pattern JSON files.

    This enum defines the canonical architectural approach names used as the name
    field in pattern JSON files and as the ArchitectureDesign.overview.style value.
    Values match Pattern.name exactly — sourced from pattern/*.json files.

    Distinct from ArchitectureDomain which describes the problem space (e.g. e-commerce,
    fintech, healthcare-integration) for pattern suitability filtering.

    Note: pattern/ contains one *-architecture.json file per entry; the count
    is verified by tests/unit/schemas/test_enums.py:test_has_N_values.
    """

    ACTOR_BASED = "actor-based"
    AIML_CENTRIC = "aiml-centric"
    API_GATEWAY = "api-gateway"
    BACKEND_FOR_FRONTEND = "backend-for-frontend"
    BLACKBOARD = "blackboard"
    BLOCKCHAIN_BASED = "blockchain-based"
    BROKER = "broker"
    COMMAND_QUERY_RESPONSIBILITY_SEGREGATION = "command-query-responsibility-segregation"
    DATA_MESH = "data-mesh"
    EDGE_COMPUTING = "edge-computing"
    ENTERPRISE_SERVICE_BUS = "enterprise-service-bus"
    EVENT_DRIVEN = "event-driven"
    EVENT_SOURCING = "event-sourcing"
    HALF_SYNC_HALF_ASYNC = "half-sync-half-async"
    HEXAGONAL = "hexagonal"
    HYBRID_CLOUD = "hybrid-cloud"
    KAPPA_ARCHITECTURE = "kappa-architecture"
    LAMBDA_ARCHITECTURE = "lambda-architecture"
    LAYERED_MONOLITH = "layered-monolith"
    MICROKERNEL_PLUGIN = "microkernel-plugin"
    MICROSERVICES = "microservices"
    MODEL_VIEW_CONTROLLER = "model-view-controller"
    MODULAR_MONOLITH = "modular-monolith"
    MONOLITHIC = "monolithic"
    MULTI_CLOUD = "multi-cloud"
    PIPE_AND_FILTER = "pipe-and-filter"
    PRESENTATION_ABSTRACTION_CONTROL = "presentation-abstraction-control"
    REACTIVE_ARCHITECTURE = "reactive-architecture"
    REFLECTION_ARCHITECTURE = "reflection-architecture"
    RULE_BASED_SYSTEM = "rule-based-system"
    SAGA = "saga"
    SERVERLESS = "serverless"
    SERVICE_MESH = "service-mesh"
    SERVICE_ORIENTED_ARCHITECTURE = "service-oriented-architecture"
    SPACE_BASED = "space-based"
    TASK_CONTROL_ARCHITECTURE = "task-control-architecture"
    STRANGLER_FIG = "strangler-fig"
    CLEAN_ARCHITECTURE = "clean-architecture"
    CLIENT_SERVER = "client-server"
    MASTER_SLAVE = "master-slave"

